### create building
POST http://localhost:3000/api/buildings
Content-Type: application/json

{
  "name": "Pavillon principal",
  "address": "7000, rue Marie-Victorin",
  "yearBuilt": 2005
}

### get all buildings
GET http://localhost:3000/api/buildings

### get health
GET http://localhost:3000/api/health
### get specific building
GET http://localhost:3000/api/buildings/2